# Generated by Django 5.2.17 on 2026-09-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'événement.", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text="Description détaillée de l'événement.")),
                ('type', models.CharField(choices=[('REUNION', 'Réunion'), ('RENDEZ_VOUS', 'Rendez-vous'), ('AUDIENCE', 'Audience'), ('DEPLACEMENT', 'Déplacement'), ('RAPPEL', 'Rappel'), ('ECHEANCE', 'Échéance'), ('AUTRE', 'Autre')], default='AUTRE', help_text="Type d'événement.", max_length=30)),
                ('date_debut', models.DateTimeField(help_text='Date et heure de début.')),
                ('date_fin', models.DateTimeField(help_text='Date et heure de fin.')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('REALISE', 'Réalisé'), ('ANNULE', 'Annulé')], default='PLANIFIE', help_text="Statut de l'événement.", max_length=20)),
                ('niveau_priorite', models.CharField(choices=[('DIRECTION', 'Direction'), ('PERSONNEL', 'Personnel')], default='PERSONNEL', help_text="Niveau de priorité. Un événement DIRECTION prime sur un événement PERSONNEL en cas de conflit d'agenda.", max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False, help_text='Indique si le rappel automatique (30 min avant) a déjà été envoyé. Utilisé par le job notifier_evenements_imminents.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'événement.")),
                ('createur', models.ForeignKey(help_text="Utilisateur qui a créé l'événement.", on_delete=django.db.models.deletion.CASCADE, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text="Utilisateurs conviés à l'événement. La relation est automatiquement propagée à leur agenda.", related_name='evenements_participes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ('-date_debut',),
            },
        ),
    ]
