# Generated by Django 5.2.17 on 2026-09-18 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'activité.", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text="Description détaillée de l'activité.")),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='OUVERTE', help_text="Statut de l'activité.", max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', help_text="Niveau de priorité de l'activité.", max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, help_text="Date de début de l'activité (optionnelle).", null=True)),
                ('date_echeance', models.DateTimeField(blank=True, help_text="Date d'échéance de l'activité (optionnelle).", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'activité.")),
                ('createur', models.ForeignKey(help_text="Utilisateur qui a créé l'activité.", on_delete=django.db.models.deletion.CASCADE, related_name='activites_creees', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(help_text="Utilisateur qui pilote l'activité.", on_delete=django.db.models.deletion.PROTECT, related_name='activites_pilotees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ('-date_creation',),
            },
        ),
    ]
