# Generated by Django 5.2.17 on 2026-09-18 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre ou objet de l'instruction.", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'instruction.")),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', help_text="Niveau de priorité de l'instruction.", max_length=20)),
                ('date_echeance', models.DateTimeField(blank=True, help_text="Date d'échéance de l'instruction (optionnelle).", null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', help_text="Statut global de l'instruction. Passe à TERMINEE uniquement quand tous les destinataires ont terminé.", max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'instruction.")),
                ('activite_cible', models.ForeignKey(blank=True, help_text="Activité ciblée par l'instruction. Mutuellement exclusif avec tache_cible (à venir).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_ciblees', to='api.activite')),
                ('emetteur', models.ForeignKey(help_text="Utilisateur qui a émis l'instruction.", on_delete=django.db.models.deletion.PROTECT, related_name='instructions_emises', to=settings.AUTH_USER_MODEL)),
                ('saisie_par', models.ForeignKey(blank=True, help_text="Utilisateur qui a saisi l'instruction au nom de l'émetteur (cas d'une délégation au secrétariat).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instruction',
                'verbose_name_plural': 'Instructions',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='InstructionDestinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', help_text="Statut d'exécution pour ce destinataire.", max_length=20)),
                ('commentaire', models.TextField(blank=True, default='', help_text="Commentaire du destinataire sur l'exécution.")),
                ('date_maj', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour du statut.')),
                ('destinataire', models.ForeignKey(help_text="Utilisateur destinataire de l'instruction.", on_delete=django.db.models.deletion.CASCADE, related_name='instructions_recues', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(help_text='Instruction concernée.', on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='api.instruction')),
            ],
            options={
                'verbose_name': "Destinataire d'instruction",
                'verbose_name_plural': "Destinataires d'instruction",
                'ordering': ('instruction', 'destinataire'),
                'unique_together': {('instruction', 'destinataire')},
            },
        ),
    ]
