# Generated by Django 5.2.17 on 2026-09-18 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_instruction_instructiondestinataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la tâche.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description détaillée de la tâche.')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Date de début de la tâche (optionnelle).', null=True)),
                ('date_echeance', models.DateTimeField(blank=True, help_text="Date d'échéance de la tâche (optionnelle).", null=True)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', help_text='Niveau de priorité de la tâche.', max_length=20)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('BLOQUEE', 'Bloquée'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', help_text='Statut actuel de la tâche.', max_length=20)),
                ('date_derniere_notif_retard', models.DateTimeField(blank=True, help_text='Date du dernier rappel de retard envoyé. Utilisé par le job marquer_taches_en_retard pour éviter le spam.', null=True)),
                ('date_derniere_notif_echeance', models.DateTimeField(blank=True, help_text="Date du dernier rappel d'échéance proche envoyé. Utilisé par le job notifier_echeances_proches pour éviter le spam.", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la tâche.')),
                ('activite', models.ForeignKey(blank=True, help_text='Activité à laquelle la tâche est rattachée (optionnelle).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api.activite')),
                ('createur', models.ForeignKey(help_text='Utilisateur qui a créé la tâche.', on_delete=django.db.models.deletion.CASCADE, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(blank=True, help_text="Instruction d'origine, si la tâche a été générée à partir d'une instruction.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_generees', to='api.instruction')),
                ('responsable', models.ForeignKey(blank=True, help_text="Utilisateur responsable de l'exécution.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.AddField(
            model_name='instruction',
            name='tache_cible',
            field=models.ForeignKey(blank=True, help_text="Tâche ciblée par l'instruction. Mutuellement exclusif avec activite_cible.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_ciblees', to='api.tache'),
        ),
    ]
