# Generated by Django 5.2.17 on 2026-09-18 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tache_instruction_tache_cible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description détaillée du blocage rencontré.')),
                ('niveau_urgence', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', help_text="Niveau d'urgence du blocage.", max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_TRAITEMENT', 'En traitement'), ('REMONTE_AU_DIRECTEUR', 'Remonté au Directeur'), ('RESOLU', 'Résolu')], default='EN_ATTENTE', help_text='Statut actuel du blocage.', max_length=30)),
                ('date_signalement', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le blocage a été signalé.')),
                ('date_resolution', models.DateTimeField(blank=True, help_text='Date à laquelle le blocage a été résolu.', null=True)),
                ('personne_sollicitee', models.ForeignKey(blank=True, help_text='Utilisateur sollicité pour résoudre le blocage (souvent le Chef de service ou le Directeur).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_sollicites', to=settings.AUTH_USER_MODEL)),
                ('resolu_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a résolu le blocage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_resolus', to=settings.AUTH_USER_MODEL)),
                ('signale_par', models.ForeignKey(help_text='Utilisateur qui a signalé le blocage.', on_delete=django.db.models.deletion.PROTECT, related_name='blocages_signales', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(help_text='Tâche sur laquelle le blocage a été signalé.', on_delete=django.db.models.deletion.CASCADE, related_name='blocages', to='api.tache')),
            ],
            options={
                'verbose_name': 'Blocage',
                'verbose_name_plural': 'Blocages',
                'ordering': ('-date_signalement',),
            },
        ),
    ]
