# Generated by Django 5.2.17 on 2026-09-18 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blocage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_delegue', models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('SECRETAIRE_DIRECTION', 'Secrétaire de Direction'), ('CHEF_SERVICE_PROJETS', 'Chef Service Projets'), ('CHEF_SERVICE_PARTENARIATS', 'Chef Service Partenariats'), ('CONSEILLERE_TECHNIQUE', 'Conseillère Technique'), ('MEMBRE_EQUIPE_APPUI', "Membre Équipe d'Appui")], help_text='Rôle attribué temporairement au délégataire.', max_length=50)),
                ('service', models.CharField(blank=True, help_text='Service concerné par la délégation (optionnel).', max_length=100, null=True)),
                ('date_debut', models.DateTimeField(help_text='Début de la période de délégation.')),
                ('date_fin', models.DateTimeField(help_text='Fin de la période de délégation.')),
                ('actif', models.BooleanField(default=True, help_text="Indique si la délégation est active. Passe à False lors d'une révocation manuelle ou d'une expiration automatique.")),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la délégation.')),
                ('delegant', models.ForeignKey(help_text='Utilisateur qui délègue son rôle.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_donnees', to=settings.AUTH_USER_MODEL)),
                ('delegataire', models.ForeignKey(help_text='Utilisateur qui reçoit temporairement le rôle.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ('-date_creation',),
            },
        ),
    ]
