# Generated by Django 5.2.17 on 2026-09-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delegation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRenduQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journaliere', models.DateField(help_text='Date à laquelle correspond ce compte-rendu.')),
                ('activites_realisees', models.TextField(blank=True, default='', help_text='Activités réalisées dans la journée.')),
                ('activites_en_cours', models.TextField(blank=True, default='', help_text='Activités toujours en cours à la fin de la journée.')),
                ('activites_non_realisees', models.TextField(blank=True, default='', help_text='Activités prévues mais non réalisées.')),
                ('difficultes', models.TextField(blank=True, default='', help_text='Difficultés rencontrées dans la journée.')),
                ('prevues_lendemain', models.TextField(blank=True, default='', help_text='Activités prévues pour le lendemain.')),
                ('est_cloture', models.BooleanField(default=False, help_text='Indique si le CRQ est clôturé. Passe à True automatiquement à 23h59 via le job cloturer_crq. Une fois clôturé, le CRQ ne peut plus être modifié sans demande de réouverture.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte-rendu.')),
                ('redacteur', models.ForeignKey(help_text='Utilisateur qui a rédigé le compte-rendu.', on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte-rendu quotidien',
                'verbose_name_plural': 'Comptes-rendus quotidiens',
                'ordering': ('-date_journaliere',),
                'unique_together': {('redacteur', 'date_journaliere')},
            },
        ),
        migrations.CreateModel(
            name='DemandeReouvertureCRQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(help_text='Motif de la demande de réouverture.')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', help_text='Statut de la demande.', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True, help_text='Date de la demande.')),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date de validation ou de refus.', null=True)),
                ('crq', models.ForeignKey(help_text='Compte-rendu concerné par la demande.', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reouverture', to='api.compterenduquotidien')),
                ('demandeur', models.ForeignKey(help_text='Utilisateur qui fait la demande de réouverture.', on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reouverture_demandees', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé ou refusé la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reouverture_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de réouverture de CRQ',
                'verbose_name_plural': 'Demandes de réouverture de CRQ',
                'ordering': ('-date_demande',),
            },
        ),
    ]
