# Generated by Django 5.2.17 on 2026-09-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_compterenduquotidien_demandereouverturecrq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Contenu du commentaire.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du commentaire.')),
                ('activite', models.ForeignKey(blank=True, help_text='Activité à laquelle le commentaire est attaché.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.activite')),
                ('auteur', models.ForeignKey(help_text='Utilisateur qui a rédigé le commentaire.', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_rediges', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(blank=True, help_text='Instruction à laquelle le commentaire est attaché.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.instruction')),
                ('tache', models.ForeignKey(blank=True, help_text='Tâche à laquelle le commentaire est attaché.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.tache')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TACHE_ASSIGNEE', 'Tâche assignée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_EN_RETARD', 'Tâche en retard'), ('TACHE_PRIORITE_ELEVEE', 'Tâche priorité élevée'), ('ACTIVITE_CREEE', 'Activité créée'), ('BLOCAGE_SIGNE', 'Blocage signalé'), ('BLOCAGE_RESOLU', 'Blocage résolu'), ('BLOCAGE_REMONTE', 'Blocage remonté'), ('INSTRUCTION_RECUE', 'Instruction reçue'), ('INSTRUCTION_ACTIVITE', 'Instruction ciblant une activité'), ('EVENEMENT_DIRECTION_PRIORITAIRE', 'Événement Direction prioritaire'), ('RAPPEL_EVENEMENT', 'Rappel événement'), ('CRQ_RAPPEL', 'Rappel CRQ'), ('CRQ_REOUVERTURE_DEMANDEE', 'Réouverture CRQ demandée'), ('CRQ_REOUVERTURE_VALIDEE', 'Réouverture CRQ validée'), ('CRQ_REOUVERTURE_REFUSEE', 'Réouverture CRQ refusée'), ('DELEGATION_ACTIVEE', 'Délégation activée'), ('DELEGATION_REVOQUEE', 'Délégation révoquée'), ('ECHEANCE_PROCHE_TACHE', 'Échéance proche (tâche)'), ('SYNTHESE_GENEREE', 'Synthèse générée'), ('UTILISATEUR_A_REASSIGNER', 'Utilisateur à réassigner'), ('UTILISATEUR_DESACTIVE', 'Utilisateur désactivé'), ('ANNULATION_MOTIVEE', 'Annulation motivée'), ('SYSTEME', 'Système')], help_text="Type de la notification (détermine l'icône et le comportement).", max_length=50)),
                ('message', models.TextField(help_text='Message de la notification.')),
                ('lue', models.BooleanField(default=False, help_text='Indique si la notification a été lue par le destinataire.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la notification.')),
                ('destinataire', models.ForeignKey(help_text='Utilisateur destinataire de la notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-date_creation',),
            },
        ),
    ]
