# Generated by Django 5.2.17 on 2026-09-18 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commentaire_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Code de l'action effectuée (ex : TACHE_REASSIGNEE, BLOCAGE_RESOLU_PAR_REATTRIBUTION, ECHEANCE_REPORTEE).", max_length=100)),
                ('details', models.TextField(blank=True, default='', help_text="Détails supplémentaires sur l'action (contexte, motif, etc.).")),
                ('date_action', models.DateTimeField(auto_now_add=True, help_text="Date à laquelle l'action a été effectuée.")),
                ('activite', models.ForeignKey(blank=True, help_text="Activité concernée par l'action.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.activite')),
                ('auteur', models.ForeignKey(help_text="Utilisateur qui a effectué l'action.", on_delete=django.db.models.deletion.PROTECT, related_name='actions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('blocage', models.ForeignKey(blank=True, help_text="Blocage concerné par l'action.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.blocage')),
                ('instruction', models.ForeignKey(blank=True, help_text="Instruction concernée par l'action.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.instruction')),
                ('tache', models.ForeignKey(blank=True, help_text="Tâche concernée par l'action.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.tache')),
            ],
            options={
                'verbose_name': 'Action historique',
                'verbose_name_plural': 'Historique des actions',
                'ordering': ('-date_action',),
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(help_text="Nom du fichier tel qu'affiché à l'utilisateur.", max_length=255)),
                ('chemin', models.CharField(help_text='Chemin physique du fichier sur le serveur.', max_length=500)),
                ('date_upload', models.DateTimeField(auto_now_add=True, help_text="Date d'import du fichier.")),
                ('activite', models.ForeignKey(blank=True, help_text='Activité à laquelle la pièce jointe est attachée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.activite')),
                ('blocage', models.ForeignKey(blank=True, help_text='Blocage auquel la pièce jointe est attachée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.blocage')),
                ('evenement', models.ForeignKey(blank=True, help_text='Événement auquel la pièce jointe est attachée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.evenement')),
                ('instruction', models.ForeignKey(blank=True, help_text='Instruction à laquelle la pièce jointe est attachée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.instruction')),
                ('tache', models.ForeignKey(blank=True, help_text='Tâche à laquelle la pièce jointe est attachée.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='api.tache')),
                ('uploade_par', models.ForeignKey(help_text='Utilisateur qui a importé le fichier.', on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes_importees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ('-date_upload',),
            },
        ),
        migrations.CreateModel(
            name='Synthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUOTIDIENNE', 'Quotidienne'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle')], help_text='Type de synthèse.', max_length=20)),
                ('periode_debut', models.DateField(help_text='Début de la période couverte par la synthèse.')),
                ('periode_fin', models.DateField(help_text='Fin de la période couverte par la synthèse.')),
                ('contenu', models.TextField(help_text='Contenu textuel de la synthèse.')),
                ('date_generation', models.DateTimeField(auto_now_add=True, help_text='Date de génération de la synthèse.')),
                ('genere_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a généré la synthèse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses_generees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synthèse',
                'verbose_name_plural': 'Synthèses',
                'ordering': ('-date_generation',),
            },
        ),
    ]
