# Generated by Django 5.2.17 on 2026-09-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_historiqueaction_piecejointe_synthese'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='cible_id',
            field=models.IntegerField(blank=True, help_text="ID de la cible au moment de l'action (conservé après suppression).", null=True),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='cible_type',
            field=models.CharField(blank=True, default='', help_text='Type de la cible : TACHE, INSTRUCTION, BLOCAGE, ACTIVITE.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='activite',
            field=models.ForeignKey(blank=True, help_text="Activité concernée par l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='api.activite'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='blocage',
            field=models.ForeignKey(blank=True, help_text="Blocage concerné par l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='api.blocage'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='instruction',
            field=models.ForeignKey(blank=True, help_text="Instruction concernée par l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='api.instruction'),
        ),
        migrations.AlterField(
            model_name='historiqueaction',
            name='tache',
            field=models.ForeignKey(blank=True, help_text="Tâche concernée par l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='api.tache'),
        ),
    ]
