# Generated by Django 5.2.17 on 2026-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_commentaire_cible_id_commentaire_cible_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueaction',
            name='cible_id',
            field=models.IntegerField(blank=True, help_text="ID de la cible au moment de l'action (conservé après suppression).", null=True),
        ),
        migrations.AddField(
            model_name='historiqueaction',
            name='cible_type',
            field=models.CharField(blank=True, default='', help_text='Type de la cible : TACHE, INSTRUCTION, BLOCAGE, ACTIVITE.', max_length=20),
        ),
    ]
