# Generated by Django 5.2.17 on 2026-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_historiqueaction_cible_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_terminaison',
            field=models.DateTimeField(blank=True, help_text="Date et heure de passage au statut TERMINEE. Renseignée automatiquement par l'action /taches/{id}/statut/ et remise à None si la tâche est rouverte.", null=True),
        ),
    ]
