# Generated by Django 5.2.17 on 2026-10-02 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def synchroniser_perimetres_chefs(apps, schema_editor):
    """
    Aligne `chef_service_delegue` sur les délégations déjà enregistrées.

    Les délégations de rôle de chef antérieures à cette migration
    n'avaient aucun effet ; ce rattrapage leur applique le périmètre
    correspondant, sans inventer de données.
    """
    Delegation = apps.get_model('api', 'Delegation')
    from django.utils import timezone

    from api.models import RoleChoice, _comme_reference

    maintenant = timezone.now()
    for delegation in Delegation.objects.select_related('delegataire', 'delegant'):
        if delegation.role_delegue not in RoleChoice.roles_chef():
            continue
        if delegation.delegataire_id is None:
            continue
        debut = _comme_reference(delegation.date_debut)
        fin = _comme_reference(delegation.date_fin)
        if delegation.actif and debut <= maintenant <= fin:
            delegation.delegataire.chef_service_delegue = delegation.delegant
            delegation.delegataire.save(update_fields=['chef_service_delegue'])


def retirer_perimetres_chefs(apps, schema_editor):
    """Rollback : plus aucun périmètre délégué."""
    Delegation = apps.get_model('api', 'Delegation')
    for delegation in Delegation.objects.select_related('delegataire'):
        if delegation.delegataire_id is None:
            continue
        delegation.delegataire.chef_service_delegue = None
        delegation.delegataire.save(update_fields=['chef_service_delegue'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tache_date_terminaison'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='chef_service_delegue',
            field=models.ForeignKey(blank=True, help_text="Chef de service adjoint désigné par une délégation en cours. Tant que ce champ est renseigné, son service constitue le périmètre d'exercice des droits de chef de service du délégataire.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_chef_service_delegue', to=settings.AUTH_USER_MODEL, verbose_name='Chef de service délégué'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='role_delegue',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('SECRETAIRE_DIRECTION', 'Secrétaire de Direction'), ('CHEF_SERVICE_PROJETS', 'Chef Service Projets'), ('CHEF_SERVICE_PARTENARIATS', 'Chef Service Partenariats'), ('CHEF_SERVICE_APPUI', 'Chef Service - Appui'), ('CONSEILLERE_TECHNIQUE', 'Conseillère Technique'), ('MEMBRE_EQUIPE_APPUI', "Membre Équipe d'Appui")], help_text='Rôle attribué temporairement au délégataire.', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('SECRETAIRE_DIRECTION', 'Secrétaire de Direction'), ('CHEF_SERVICE_PROJETS', 'Chef Service Projets'), ('CHEF_SERVICE_PARTENARIATS', 'Chef Service Partenariats'), ('CHEF_SERVICE_APPUI', 'Chef Service - Appui'), ('CONSEILLERE_TECHNIQUE', 'Conseillère Technique'), ('MEMBRE_EQUIPE_APPUI', "Membre Équipe d'Appui")], default='MEMBRE_EQUIPE_APPUI', help_text="Rôle métier de l'utilisateur dans la direction.", max_length=50),
        ),
        migrations.RunPython(
            synchroniser_perimetres_chefs,
            retirer_perimetres_chefs,
        ),
    ]
