# Generated by Django 5.2.17 on 2026-10-02 16:25

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_utilisateur_chef_service_delegue'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', api.models.UtilisateurManager()),
            ],
        ),
    ]
