# Generated by Django 5.2.17 on 2026-10-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('BLOQUEE', 'Bloquée'), ('A_VALIDER', 'À valider'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='A_FAIRE', help_text='Statut actuel de la tâche.', max_length=20),
        ),
    ]
