# Generated by Django 5.2.17 on 2026-10-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_tache_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TACHE_ASSIGNEE', 'Tâche assignée'), ('TACHE_MODIFIEE', 'Tâche modifiée'), ('TACHE_EN_RETARD', 'Tâche en retard'), ('TACHE_PRIORITE_ELEVEE', 'Tâche priorité élevée'), ('TACHE_A_VALIDER', 'Tâche à valider'), ('TACHE_VALIDEE', 'Tâche validée'), ('TACHE_REJETEE', 'Tâche rejetée'), ('ACTIVITE_CREEE', 'Activité créée'), ('BLOCAGE_SIGNE', 'Blocage signalé'), ('BLOCAGE_RESOLU', 'Blocage résolu'), ('BLOCAGE_REMONTE', 'Blocage remonté'), ('INSTRUCTION_RECUE', 'Instruction reçue'), ('INSTRUCTION_ACTIVITE', 'Instruction ciblant une activité'), ('EVENEMENT_DIRECTION_PRIORITAIRE', 'Événement Direction prioritaire'), ('RAPPEL_EVENEMENT', 'Rappel événement'), ('CRQ_RAPPEL', 'Rappel CRQ'), ('CRQ_REOUVERTURE_DEMANDEE', 'Réouverture CRQ demandée'), ('CRQ_REOUVERTURE_VALIDEE', 'Réouverture CRQ validée'), ('CRQ_REOUVERTURE_REFUSEE', 'Réouverture CRQ refusée'), ('DELEGATION_ACTIVEE', 'Délégation activée'), ('DELEGATION_REVOQUEE', 'Délégation révoquée'), ('ECHEANCE_PROCHE_TACHE', 'Échéance proche (tâche)'), ('SYNTHESE_GENEREE', 'Synthèse générée'), ('UTILISATEUR_A_REASSIGNER', 'Utilisateur à réassigner'), ('UTILISATEUR_DESACTIVE', 'Utilisateur désactivé'), ('ANNULATION_MOTIVEE', 'Annulation motivée'), ('SYSTEME', 'Système')], help_text="Type de la notification (détermine l'icône et le comportement).", max_length=50),
        ),
    ]
