# Generated by Django 5.2.17 on 2026-10-03 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_blocage_date_contestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueaction',
            name='auteur',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action. Nul pour les actions automatiques du système (escalade de blocage).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
